apiVersion: v1
kind: Service
metadata:
  labels:
    app: customerservice
    component: customerservice
  name: customerservice
spec:
  ports:
  - port: 80
  selector:
    app: customerservice
    component: customerservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customerservice
spec:
  template:
    metadata:
      labels:
        app: customerservice
        component: customerservice
    spec:
      imagePullSecrets:
       - name: regsecret
      containers:
      - name: customerservice
        image: localhost:5000/customerservice:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10