apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderservice
    component: orderservice
  name: orderservice
spec:
  ports:
  - port: 80
  selector:
    app: orderservice
    component: orderservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderservice
spec:
  template:
    metadata:
      labels:
        app: orderservice
        component: orderservice
    spec:
      containers:
      - name: orderservice
        image: localhost:5000/orderservice:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80