apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    name: http
  - port: 9300
    protocol: TCP
    name: transport
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  template: 
    metadata:
      labels:
        app: elasticsearch
    spec:
      serviceAccount: elasticsearch
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
        ports:
        - containerPort: 9200
        - containerPort: 9300
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            memory: 512Mi
            cpu: "0.5"
          limits:
            cpu: 1
            memory: 1024Mi

        env:
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "cluster.name"
          value: "cpp"
        - name: "discovery.type"
          value: "single-node"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"

