apiVersion: v1
kind: ConfigMap
metadata:
  name: customerserviceconf
  namespace: packt
data:
  messaging: |
    KafkaConsumer:
      Server: kafkaserver
      Topics:
        - ReactiveMicroservices      
      GroupId: customer-service
      TimeOut: "00:00:01"
    KafkaProducer:
      Server: kafkaserver
      MaxRetries: 2
      MessageTimeout: "00:00:15"    